var Constants = {

  INDEX_RECEIVED: "INDEX_RECEIVED",
  THREAD_RECEIVED: "THREAD_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  SEARCH_RESULTS_RECEIVED: "SEARCH_RESULTS_RECEIVED"

};

module.exports = Constants;
